option(AYUGRAM_ENABLE_COMPILATION_CACHE "Cache C/C++ compilation with sccache." OFF)

if (NOT AYUGRAM_ENABLE_COMPILATION_CACHE)
    return()
endif()

find_program(AYUGRAM_SCCACHE_EXECUTABLE NAMES sccache REQUIRED)

if (CMAKE_GENERATOR STREQUAL "Xcode")
    set(CMAKE_XCODE_ATTRIBUTE_C_COMPILER_LAUNCHER "${AYUGRAM_SCCACHE_EXECUTABLE}")
    set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_MODULES NO)
    set(CMAKE_XCODE_ATTRIBUTE_COMPILER_INDEX_STORE_ENABLE NO)
    set(CMAKE_XCODE_ATTRIBUTE_CLANG_USE_RESPONSE_FILE NO)
elseif (CMAKE_GENERATOR MATCHES "Ninja|Makefiles")
    set(CMAKE_C_COMPILER_LAUNCHER "${AYUGRAM_SCCACHE_EXECUTABLE}")
    set(CMAKE_CXX_COMPILER_LAUNCHER "${AYUGRAM_SCCACHE_EXECUTABLE}")
    set(CMAKE_OBJC_COMPILER_LAUNCHER "${AYUGRAM_SCCACHE_EXECUTABLE}")
    set(CMAKE_OBJCXX_COMPILER_LAUNCHER "${AYUGRAM_SCCACHE_EXECUTABLE}")
else()
    message(FATAL_ERROR "Compilation caching requires Ninja, Makefiles, or Xcode.")
endif()

function(ayugram_cache_msvc_targets directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach (target IN LISTS targets)
        get_target_property(target_type ${target} TYPE)
        if (target_type STREQUAL "INTERFACE_LIBRARY" OR target_type STREQUAL "UTILITY")
            continue()
        endif()

        set_property(TARGET ${target} PROPERTY MSVC_DEBUG_INFORMATION_FORMAT Embedded)
        get_target_property(headers ${target} PRECOMPILE_HEADERS)
        if (headers)
            # sccache cannot cache MSVC PCH use; retain the headers as forced includes.
            set_property(TARGET ${target} PROPERTY DISABLE_PRECOMPILE_HEADERS ON)
            foreach (header IN LISTS headers)
                target_compile_options(${target} PRIVATE "$<$<BOOL:${header}>:/FI${header}>")
            endforeach()
        endif()
    endforeach()

    get_property(subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach (subdirectory IN LISTS subdirectories)
        ayugram_cache_msvc_targets("${subdirectory}")
    endforeach()
endfunction()

if (MSVC)
    cmake_language(DEFER CALL ayugram_cache_msvc_targets "${CMAKE_CURRENT_SOURCE_DIR}")
endif()
